import fs from "fs";
import path from "path";

async function createAffiliatePage(pageName, providerName, url) {
  if (!pageName || !providerName || !url) return;

  const folder = path.join(process.cwd(), "app", "affiliate", pageName);
  const file = path.join(folder, "page.js");

  if (!fs.existsSync(folder)) {
    fs.mkdirSync(folder, { recursive: true });
  }

  const content = `
export const metadata = {
  title: "${providerName} — Auto Affiliate Page",
  description: "Automatically generated affiliate landing page for ${providerName}."
};

export default function Page() {
  return (
    <div style={{ padding: "40px" }}>
      <h1>${providerName}</h1>
      <p>This page was auto-generated by AuraFlowAI.</p>
      <a href="${url}" target="_blank" style={{ color: "blue" }}>
        Visit ${providerName}
      </a>
    </div>
  );
}
`;

  fs.writeFileSync(file, content, "utf8");
  return true;
}

export default createAffiliatePage;
